update code using git pull

diff --git a/admin/trunk/scripts/vidaas-monitoringnode-install b/admin/trunk/scripts/vidaas-monitoringnode-install
--- a/admin/trunk/scripts/vidaas-monitoringnode-install
+++ b/admin/trunk/scripts/vidaas-monitoringnode-install
@@ -28,8 +28,15 @@ source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/postgres-crea
 source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/postgres-createrole.sh rhqadmindev rhqdev
 source $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/shared/postgres-createrole.sh rhqadmintest rhqtest
 
-mkdir -p $monitor_git
-if cd $monitor_git && git clone git://git.fedorahosted.org/git/rhq/rhq.git ; then
+if ! [ -d $monitor_git ] ; then
+  mkdir -p $monitor_git
+  if cd $monitor_git && git clone git://git.fedorahosted.org/git/rhq/rhq.git ; then
+    echo "git clone complete"
+  else
+    echo "git clone failed" ; exit 1
+  fi
+fi
+if cd $monitor_git && git pull ; then
   source $vidaas_admin_repo_path/admin/$vidaas_branch/services/rhq/settings.xml.sh > $monitor_git/rhq/etc/m2/settings.xml
   if cd $monitor_git/rhq/ && mvn -Penterprise,dev -Ddbsetup install ; then
     echo "build complete"
