script changes

diff --git a/admin/scripts/vidaas-projectnode-install b/admin/scripts/vidaas-projectnode-install
--- a/admin/scripts/vidaas-projectnode-install
+++ b/admin/scripts/vidaas-projectnode-install
@@ -2,15 +2,24 @@
 
 #defaults
 vidaas_home=/opt/VIDaaSData/
-jboss_install_dir=/opt/
-seam_install_dir=/opt/
+#vidaas_home=/var/lib/VIDaaSData/
+target_dir=/opt/
+jboss_install_dir=$target_dir #obsolete
+seam_install_dir=$target_dir #obsolete
 
 #load settings
-source /etc/vidaas/settings
+. /etc/vidaas/settings
+. /etc/vidaas/env
 
-projectnode_packages="maven2 less vim unzip postgresql libmysql-java libpg-java openjdk-6-jdk ant apache2 libapache2-mod-jk daemontools patch"
+projectnode_packages="maven2 less vim unzip postgresql libmysql-java libpg-java openjdk-6-jdk ant apache2 libapache2-mod-jk daemontools patch pwgen"
 
-if ! id vidaas > /dev/null ; then
+#save env
+if [ -z "$JAVA_HOME" ] ; then
+  export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/
+  echo "export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/" >> /etc/vidaas/env
+fi
+
+if ! id vidaas 2>&1 > /dev/null ; then
   echo "Creating vidaas system user"
   if ! adduser --system --home "$vidaas_home" --disabled-login --group vidaas --shell /bin/bash ; then
     echo "failed to create vidaas user"
@@ -18,30 +27,170 @@ if ! id vidaas > /dev/null ; then
   fi
 fi
 
-if ! apt-get -qqy install $projectnode_packages ; then
+echo "Installing project node packages $projectnode_packages"
+if ! DEBIAN_FRONTEND=noninteractive apt-get -qqy install $projectnode_packages ; then
   echo "failed to install required packages"
   exit 1
 fi
 
 cd
-if ! wget --no-verbose -O /tmp/jboss-5.1.0.GA-jdk6.zip http://downloads.sourceforge.net/project/jboss/JBoss/JBoss-5.1.0.GA/jboss-5.1.0.GA-jdk6.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fjboss%2Ffiles%2FJBoss%2FJBoss-5.1.0.GA%2F ; then
-  rm /tmp/jboss-5.1.0.GA-jdk6.zip
-  echo "Unable to download jboss 5.1"
-  exit 1
+if ! [ -f /tmp/jboss-5.1.0.GA-jdk6.zip ] ; then
+  echo "Downloading jboss..."
+  if ! wget --no-verbose -O /tmp/jboss-5.1.0.GA-jdk6.zip http://downloads.sourceforge.net/project/jboss/JBoss/JBoss-5.1.0.GA/jboss-5.1.0.GA-jdk6.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fjboss%2Ffiles%2FJBoss%2FJBoss-5.1.0.GA%2F ; then
+    rm /tmp/jboss-5.1.0.GA-jdk6.zip
+    echo "Unable to download jboss 5.1"
+    exit 1
+  fi
 fi
-if ! wget --no-verbose -O /tmp/jboss-seam-2.2.2.Final.tar.gz http://downloads.sourceforge.net/project/jboss/JBoss%20Seam/2.2.2.Final/jboss-seam-2.2.2.Final.tar.gz ; then
-  rm /tmp/jboss-seam-2.2.2.Final.tar.gz
-  echo "Unable to download Seam 2.2.2"
-  exit 1
+if ! [ -f /tmp/jboss-seam-2.2.2.Final.tar.gz ] ; then 
+  echo "Downloading seam..."
+  if ! wget --no-verbose -O /tmp/jboss-seam-2.2.2.Final.tar.gz http://downloads.sourceforge.net/project/jboss/JBoss%20Seam/2.2.2.Final/jboss-seam-2.2.2.Final.tar.gz ; then
+    rm /tmp/jboss-seam-2.2.2.Final.tar.gz
+    echo "Unable to download Seam 2.2.2"
+    exit 1
+  fi
 fi
 
-cd /opt
-#rm jboss
-tar -xzf /tmp/jboss-5.1.0.GA-jdk6.zip
+echo "Stopping jboss..."
+/etc/init.d/jboss51 stop 2>&1 > /dev/null
+echo "Deleting old jboss installation..."
+rm -rf $jboss_install_dir/jboss-5.1.0.GA
+rm -rf /tmp/jboss-setup/ 2>&1 > /dev/null
+
+mkdir -p /tmp/jboss-setup/
+if cd /tmp/jboss-setup/ ; then
+  echo "extracting jboss..."
+  if unzip -q /tmp/jboss-5.1.0.GA-jdk6.zip ; then
+    if ! mv -f * $jboss_install_dir ; then
+      echo "failed moving jboss to $jboss_install_dir"
+      exit 1
+    fi
+    #convenience symlink
+    ln -s $jboss_install_dir/jboss-5.1.0.GA $jboss_install_dir/jboss
+    #chown to vidaas system user
+    chown -R vidaas:vidaas $jboss_install_dir/jboss-5.1.0.GA
+    #sanity check
+    if [ ! -f $jboss_install_dir/jboss/bin/run.sh ] ; then
+      echo "Can't find $jboss_install_dir/jboss/bin/run.sh - install failed"
+      exit 1
+    fi
+    #save env
+    export JBOSS_HOME=$jboss_install_dir/jboss/
+    echo "export JBOSS_HOME=$JBOSS_HOME" >> /etc/vidaas/env
+    #remove vulnerable/unwanted files
+    rm -rf $jboss_install_dir/jboss/server/default/deploy/admin-console.war
+    rm -rf $jboss_install_dir/jboss/server/default/deploy/jmx-console.war
+    rm -rf $jboss_install_dir/jboss/server/default/deploy/management
+    #install startup script
+    cp $vidaas_admin_repo_path/admin/root/etc/init.d/jboss51 /etc/init.d/jboss51
+    chmod +x /etc/init.d/jboss51
+    if ! update-rc.d jboss51 defaults ; then
+      echo "failed to install jboss init script"
+      exit 1
+    fi
+    #symlink database drivers
+    ln -s /usr/share/java/mysql.jar $JBOSS_HOME/server/default/lib/mysql.jar
+    ln -s /usr/share/java/postgresql.jar $JBOSS_HOME/server/default/lib/postgresql.jar
+    mkdir -p $target_dir/DatabaseDrivers/
+    ln -s /usr/share/java/postgresql.jar $target_dir/DatabaseDrivers/postgresql.jar
+  else
+    echo "failed to unzip jboss"
+    exit 1
+  fi
+fi
+
+if ! [ -e /etc/vidaas/cred_sudamihAdmin ] ; then
+  if ! touch /etc/vidaas/cred_sudamihAdmin && chmod 600 /etc/vidaas/cred_sudamihAdmin ; then
+    echo "Failed to create cred file /etc/vidaas/cred_sudamihAdmin" ; exit 1
+  fi
+  if ! pwgen -s 12 1 | tr -d '\n' >> /etc/vidaas/cred_sudamihAdmin ; then
+    echo "Failed to create cred file /etc/vidaas/cred_sudamihAdmin" ; exit 1
+  fi
+  if ! su -p -c "psql -c \"CREATE ROLE \\\"sudamihAdmin\\\" ENCRYPTED PASSWORD '`cat /etc/vidaas/cred_sudamihAdmin`' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;\"" postgres ; then
+    echo "failed to create sudamihAdmin postgres role" ; exit 1
+  fi
+  echo "creating database..."
+  if ! su -p -c "createdb -O sudamihAdmin -E UTF8 sudamihtestdb" postgres ; then
+    echo "failed to create postgres database"
+    exit 1
+  fi
+fi
+
+if ! DEBIAN_FRONTEND=noninteractive apt-get -qqy install mysql-server ; then
+  echo "mysql-server installation failed"
+  exit 1
+fi
+if ! [ -e /etc/vidaas/cred_mysqlroot ] ; then
+  if ! touch /etc/vidaas/cred_mysqlroot && chmod 600 /etc/vidaas/cred_mysqlroot ; then
+    echo "Failed to create cred file /etc/vidaas/cred_mysqlroot" ; exit 1
+  fi
+  if ! pwgen -s 12 1 | tr -d '\n' >> /etc/vidaas/cred_mysqlroot ; then
+    echo "Failed to create cred file /etc/vidaas/cred_mysqlroot" ; exit 1
+  fi
+  if ! mysqladmin -u root password `cat /etc/vidaas/cred_mysqlroot` ; then
+    echo "Failed to set mysql root password" ; exit 1
+  fi
+  service mysql restart
+fi
+
+echo "Building vidaas sources..."
+if ! su -c "cd ~ && svn checkout https://vidaas.googlecode.com/svn/vidaas3/trunk && cd trunk/vidaas && mvn package" vidaas 2>&1 > /var/log/vidaas-build.log ; then
+  echo "Build failed see /var/log/vidaas-build.log" ; exit 1
+fi
+
+echo "Deploying webapp"
+#TODO move to template
+if touch $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml && chown vidaas:vidaas $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml && chmod 600 $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml ; then
+(
+cat <<EndOfFile
+<?xml version="1.0" encoding="UTF-8"?>
+<datasources>
+   <local-tx-datasource>
+      <jndi-name>vidaasDatasource</jndi-name>
+      <use-java-context>true</use-java-context>
+      <connection-url>jdbc:mysql://localhost:3306/vidaas_v3</connection-url>
+      <driver-class>com.mysql.jdbc.Driver</driver-class>
+      <user-name>root</user-name>
+      <password>`cat /etc/vidaas/cred_mysqlroot`</password>
+   </local-tx-datasource>
+</datasources>
+EndOfFile
+) > $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml
+else
+  echo "could not create vidaas3-ds.xml" ; exit 1
+fi
+
+#TODO move to template
+if touch $JBOSS_HOME/server/default/deploy/vidaas-service.xml && chown vidaas:vidaas $JBOSS_HOME/server/default/deploy/vidaas-service.xml && chmod 600 $JBOSS_HOME/server/default/deploy/vidaas-service.xml ; then
+(
+cat <<EndOfFile
+<mbean code="org.jboss.varia.property.SystemPropertiesService" name="jboss.util:type=Service,name=VIDaaSProperties">
+  <attribute name="Properties">
+    seamLocaion=$target_dir/seam/
+    serverLocation=$JBOSS_HOME
+    serverURL=http://`/sbin/ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`/
+    VIDaaSDataLocation=$vidaas_home
+    jdbcDriverJar=$target_dir/DatabaseDrivers/postgresql.jar
+ </attribute>
+</mbean>
+EndOfFile
+) > $JBOSS_HOME/server/default/deploy/vidaas-service.xml
+else
+  echo "Could not create vidaas-service.xml" ; exit 1
+fi
+
+#su -m -c "cp -r ~/ " vidaas
+
+#TODO move to template
+#chmod 600 
+
+#cd $seam_install_dir
 #rm seam
-tar -xzf /tmp/jboss-seam-2.2.2.Final.tar.gz
+#tar -xzf /tmp/jboss-seam-2.2.2.Final.tar.gz
+
+#symlink database drivers
 
 # is fixed but needs testing (remove when tested)
-chown vidaas:vidaas /opt
+#chown vidaas:vidaas /opt
 
 
