script updates

diff --git a/admin/scripts/vidaas-projectnode-install b/admin/scripts/vidaas-projectnode-install
--- a/admin/scripts/vidaas-projectnode-install
+++ b/admin/scripts/vidaas-projectnode-install
@@ -1,17 +1,24 @@
 #!/bin/bash
 
 #defaults
-vidaas_home=/opt/VIDaaSData
+vidaas_home=/opt/VIDaaSData/
+jboss_install_dir=/opt/
+seam_install_dir=/opt/
 
 #load settings
 source /etc/vidaas/settings
 
-if ! adduser --system --home "$vidaas_home" --disabled-login --group vidaas --shell /bin/bash ; then
-  echo "failed to create vidaas user"
-  exit 1
+projectnode_packages="maven2 less vim unzip postgresql libmysql-java libpg-java openjdk-6-jdk ant apache2 libapache2-mod-jk daemontools patch"
+
+if ! id vidaas > /dev/null ; then
+  echo "Creating vidaas system user"
+  if ! adduser --system --home "$vidaas_home" --disabled-login --group vidaas --shell /bin/bash ; then
+    echo "failed to create vidaas user"
+    exit 1
+  fi
 fi
 
-if ! apt-get -y install maven2 less vim unzip postgresql libmysql-java libpg-java openjdk-6-jdk ant apache2 libapache2-mod-jk daemontools patch ; then
+if ! apt-get -qqy install $projectnode_packages ; then
   echo "failed to install required packages"
   exit 1
 fi
