minimalistic startup script

diff --git a/admin/root/etc/init.d/jboss51 b/admin/root/etc/init.d/jboss51
--- a/admin/root/etc/init.d/jboss51
+++ b/admin/root/etc/init.d/jboss51
@@ -48,14 +48,9 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --background --quiet --pidfile $PIDFILE --exec $DAEMON --chuid vidaas:vidaas --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --background --quiet --pidfile $PIDFILE --exec $DAEMON --chuid vidaas:vidaas -- \
-		$DAEMON_ARGS \
-		|| return 2
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+	setuidgid vidaas $JBOSS_HOME/bin/run.sh > /dev/null &
+	# There is no way to find out if jboss started other than checking logs
+	return 0
 }
 
 #
@@ -68,20 +63,8 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
+	setuidgid vidaas $JBOSS_HOME/bin/shutdown.sh -S
+	return 0
 }
 
 #
@@ -114,9 +97,9 @@ case "$1" in
 		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
-  status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
+  #status)
+       #status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       #;;
   #reload|force-reload)
 	#
 	# If do_reload() is not implemented then leave this commented out
@@ -126,31 +109,31 @@ case "$1" in
 	#do_reload
 	#log_end_msg $?
 	#;;
-  restart|force-reload)
+  #restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+	#log_daemon_msg "Restarting $DESC" "$NAME"
+	#do_stop
+	#case "$?" in
+	#  0|1)
+#		do_start
+	#	case "$?" in
+	#		0) log_end_msg 0 ;;
+	#		1) log_end_msg 1 ;; # Old process is still running
+	#		*) log_end_msg 1 ;; # Failed to start
+	#	esac
+	#	;;
+	#  *)
+	#  	# Failed to stop
+	#	log_end_msg 1
+	#	;;
+	#esac
+	#;;
   *)
 	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop}" >&2
 	exit 3
 	;;
 esac
