merged with trunk

diff --git a/admin/branches/WithRoles/scripts/vidaas-projectnode-install b/admin/branches/WithRoles/scripts/vidaas-projectnode-install
--- a/admin/branches/WithRoles/scripts/vidaas-projectnode-install
+++ b/admin/branches/WithRoles/scripts/vidaas-projectnode-install
@@ -5,6 +5,8 @@ vidaas_home=/var/lib/VIDaaSData/
 target_dir=/opt/
 vidaas_jboss51_url=http://downloads.sourceforge.net/project/jboss/JBoss/JBoss-5.1.0.GA/jboss-5.1.0.GA-jdk6.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fjboss%2Ffiles%2FJBoss%2FJBoss-5.1.0.GA%2F
 vidaas_seam222_url=http://downloads.sourceforge.net/project/jboss/JBoss%20Seam/2.2.2.Final/jboss-seam-2.2.2.Final.tar.gz
+vidaas_source_revision=HEAD
+vidaas_designer=false
 
 # load settings
 . /etc/vidaas/bootstrap-settings
@@ -37,12 +39,14 @@ if ! DEBIAN_FRONTEND=noninteractive apt-get -qqy install $projectnode_packages ;
 fi
 
 cd
-if ! [ -f /tmp/jboss-5.1.0.GA-jdk6.zip ] ; then
-  echo "Downloading jboss..."
-  if ! wget --no-verbose -O /tmp/jboss-5.1.0.GA-jdk6.zip $vidaas_jboss51_url ; then
-    rm /tmp/jboss-5.1.0.GA-jdk6.zip
-    echo "Unable to download jboss 5.1"
-    exit 1
+if [ ! -f $target_dir/jboss/bin/run.sh ] ; then
+  if ! [ -f /tmp/jboss-5.1.0.GA-jdk6.zip ] ; then
+    echo "Downloading jboss..."
+    if ! wget --no-verbose -O /tmp/jboss-5.1.0.GA-jdk6.zip $vidaas_jboss51_url ; then
+      rm /tmp/jboss-5.1.0.GA-jdk6.zip
+      echo "Unable to download jboss 5.1"
+      exit 1
+    fi
   fi
 fi
 if ! [ -f /tmp/jboss-seam-2.2.2.Final.tar.gz ] ; then 
@@ -56,42 +60,43 @@ fi
 
 echo "Stopping jboss..."
 service jboss51 stop
-echo "Deleting old jboss installation..."
-rm -rf $target_dir/jboss-5.1.0.GA
 
-echo "Extracting jboss..."
-if cd $target_dir && unzip -q /tmp/jboss-5.1.0.GA-jdk6.zip ; then
-  #convenience symlink
-  ln -s $target_dir/jboss-5.1.0.GA $target_dir/jboss
-  #chown to vidaas system user
-  chown -R vidaas:vidaas $target_dir/jboss-5.1.0.GA
-  #sanity check
-  if [ ! -f $target_dir/jboss/bin/run.sh ] ; then
-    echo "Can't find $target_dir/jboss/bin/run.sh - install failed" ; exit 1
+if [ ! -f $target_dir/jboss/bin/run.sh ] ; then
+  echo "Extracting jboss..."
+  if cd $target_dir && unzip -q /tmp/jboss-5.1.0.GA-jdk6.zip ; then
+    #convenience symlink
+    ln -s $target_dir/jboss-5.1.0.GA $target_dir/jboss
+    #sanity check
+    if [ ! -f $target_dir/jboss/bin/run.sh ] ; then
+      echo "Can't find $target_dir/jboss/bin/run.sh - install failed" ; exit 1
+    fi
+  else
+    echo "failed to unzip jboss" ; exit 1
   fi
-  #save env
-  export JBOSS_HOME=$target_dir/jboss/
-  echo "export JBOSS_HOME=$JBOSS_HOME" >> /etc/vidaas/env
-  #remove vulnerable/unwanted files
-  rm -rf $target_dir/jboss/server/default/deploy/admin-console.war
-  rm -rf $target_dir/jboss/server/default/deploy/jmx-console.war
-  rm -rf $target_dir/jboss/server/default/deploy/management
-  #install startup script
-  cp $vidaas_admin_repo_path/admin/$vidaas_branch/root/etc/init.d/jboss51 /etc/init.d/jboss51
-  chmod +x /etc/init.d/jboss51
-  if ! update-rc.d jboss51 defaults ; then
-    echo "failed to install jboss init script" ; exit 1
-  fi
-  #symlink database drivers
-  ln -s /usr/share/java/mysql.jar $JBOSS_HOME/server/default/lib/mysql.jar
-  ln -s /usr/share/java/postgresql.jar $JBOSS_HOME/server/default/lib/postgresql.jar
-  #not sure this is still required. TODO check with asif
-  mkdir -p $target_dir/DatabaseDrivers/
-  if ! [ -h $target_dir/DatabaseDrivers/postgresql.jar ] ; then
-    ln -s /usr/share/java/postgresql.jar $target_dir/DatabaseDrivers/postgresql.jar
-  fi
-else
-  echo "failed to unzip jboss" ; exit 1
+fi
+
+#chown to vidaas system user
+chown -R vidaas:vidaas $target_dir/jboss-5.1.0.GA
+#save env
+export JBOSS_HOME=$target_dir/jboss/
+echo "export JBOSS_HOME=$JBOSS_HOME" >> /etc/vidaas/env
+#remove vulnerable/unwanted files
+rm -rf $target_dir/jboss/server/default/deploy/admin-console.war
+rm -rf $target_dir/jboss/server/default/deploy/jmx-console.war
+rm -rf $target_dir/jboss/server/default/deploy/management
+#install startup script
+cp $vidaas_admin_repo_path/admin/$vidaas_branch/root/etc/init.d/jboss51 /etc/init.d/jboss51
+chmod +x /etc/init.d/jboss51
+if ! update-rc.d jboss51 defaults ; then
+  echo "failed to install jboss init script" ; exit 1
+fi
+#symlink database drivers
+ln -s /usr/share/java/mysql.jar $JBOSS_HOME/server/default/lib/mysql.jar
+ln -s /usr/share/java/postgresql.jar $JBOSS_HOME/server/default/lib/postgresql.jar
+#not sure this is still required. TODO check with asif
+mkdir -p $target_dir/DatabaseDrivers/
+if ! [ -h $target_dir/DatabaseDrivers/postgresql.jar ] ; then
+  ln -s /usr/share/java/postgresql.jar $target_dir/DatabaseDrivers/postgresql.jar
 fi
 
 echo "Deleting old seam installation..."
@@ -157,17 +162,7 @@ else
 fi
 
 echo "Building vidaas sources..."
-if su -c "cd ~ && svn --quiet checkout https://vidaas.googlecode.com/svn/vidaas3/$vidaas_branch" vidaas ; then
-  #patch dreaded sudamih.properties
-(
-cat <<EndOfFile
-uk.ac.ox.oucs.sudamih.adminUserName = sudamihAdmin
-uk.ac.ox.oucs.sudamih.adminUserNamePW = `cat /etc/vidaas/cred_sudamihAdmin`
-uk.ac.ox.oucs.sudamih.databaseName = sudamihtestdb
-uk.ac.ox.oucs.sudamih.driverName = org.postgresql.Driver
-uk.ac.ox.oucs.sudamih.databaseURL = jdbc:postgresql:
-EndOfFile
-) > $vidaas_home/$vidaas_branch/vidaas/src/hot/uk/ac/ox/oucs/vidaas/manager/sudamih.properties
+if su -c "cd ~ && svn --quiet --revision $vidaas_source_revision checkout https://vidaas.googlecode.com/svn/vidaas3/$vidaas_branch" vidaas ; then
   if ! su -c "cd ~/$vidaas_branch/vidaas/ && mvn package" vidaas 2>&1 > /var/log/vidaas-build.log ; then
     echo "Build failed see /var/log/vidaas-build.log" ; exit 1
   fi
@@ -176,76 +171,52 @@ else
 fi
 
 echo "Deploying webapp"
-#TODO move to template
+# set permissions to 600 because it contains credentials
 if touch $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml && chown vidaas:vidaas $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml && chmod 600 $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml ; then
-(
-cat <<EndOfFile
-<?xml version="1.0" encoding="UTF-8"?>
-<datasources>
-   <local-tx-datasource>
-      <jndi-name>vidaasDatasource</jndi-name>
-      <use-java-context>true</use-java-context>
-      <connection-url>jdbc:mysql://localhost:3306/vidaas_v3</connection-url>
-      <driver-class>com.mysql.jdbc.Driver</driver-class>
-      <user-name>root</user-name>
-      <password>`cat /etc/vidaas/cred_mysqlroot`</password>
-   </local-tx-datasource>
-</datasources>
-EndOfFile
-) > $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml
+  source $vidaas_admin_repo_path/admin/$vidaas_branch/deploy/vidaas3-ds.xml.sh > $JBOSS_HOME/server/default/deploy/vidaas3-ds.xml
 else
   echo "could not create vidaas3-ds.xml" ; exit 1
 fi
 
-#TODO move to template
+# set permissions to 600 because it contains credentials
 if touch $JBOSS_HOME/server/default/deploy/vidaas-service.xml && chown vidaas:vidaas $JBOSS_HOME/server/default/deploy/vidaas-service.xml && chmod 600 $JBOSS_HOME/server/default/deploy/vidaas-service.xml ; then
-(
-cat <<EndOfFile
-<mbean code="org.jboss.varia.property.SystemPropertiesService" name="jboss.util:type=Service,name=VIDaaSProperties">
-  <attribute name="Properties">
-    seamLocaion=$target_dir/seam/
-    serverLocation=$JBOSS_HOME
-    serverURL=http://`/sbin/ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`/
-    VIDaaSDataLocation=$vidaas_home
-    jdbcDriverJar=/usr/share/java/postgresql.jar
- </attribute>
-</mbean>
-EndOfFile
-) > $JBOSS_HOME/server/default/deploy/vidaas-service.xml
+  source $vidaas_admin_repo_path/admin/$vidaas_branch/deploy/vidaas-service.xml.sh > $JBOSS_HOME/server/default/deploy/vidaas-service.xml
 else
   echo "Could not create vidaas-service.xml" ; exit 1
 fi
 
-#deploy war file
+# (re-)deploy war file
+rm -rf $JBOSS_HOME/server/default/deploy/vidaas.war
 if ! su -c "cp -r ~/$vidaas_branch/vidaas/target/vidaas $JBOSS_HOME/server/default/deploy/vidaas.war" vidaas ; then
   echo "Deployment to appserver failed" ; exit 1
+fi
+
+if [ "$vidaas_designer" == "true" ] ; then
+  if su -c "mkdir $vidaas_home/designer ; cd $vidaas_home/designer && svn --quiet checkout https://vidaas.googlecode.com/svn/SQLDesigner/trunk" vidaas ; then
+    if ! su -c "cp -r $vidaas_home/designer/trunk/resources/jQuerySQLDesigner-ds.xml $JBOSS_HOME/server/default/deploy/jQuerySQLDesigner-ds.xml" vidaas ; then
+      echo "Deployment to appserver failed" ; exit 1
+    fi
+    # (re-)deploy war file
+    rm -rf $JBOSS_HOME/server/default/deploy/jQuerySQLDesigner.war
+    if ! su -c "cp -r $vidaas_home/designer/trunk/jQuerySQLDesigner.war $JBOSS_HOME/server/default/deploy/jQuerySQLDesigner.war" vidaas ; then
+      echo "Deployment to appserver failed" ; exit 1
+    fi
+  else
+    echo "code checkout failed" ; exit 1
+  fi
 fi
 
 service jboss51 start
 
 #apache config
-#TODO move to template
 if ! [ -h /etc/apache2/mods-enabled/rewrite.load ] ; then
   ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load
 fi
-(
-cat <<EndOfFile
-JkWorkerProperty worker.list=vidaas
-JkWorkerProperty worker.vidaas.port=8009
-<VirtualHost *:80>
-    ServerAdmin webmaster@localhost
-    #redirect docroot
-    RewriteEngine on
-    RewriteRule ^/$ /vidaas/ [R]
-    #mount vidaas
-    JkMount /* vidaas
-    #logging
-    ErrorLog \${APACHE_LOG_DIR}/error.log
-    LogLevel warn
-    CustomLog \${APACHE_LOG_DIR}/access.log combined
-</VirtualHost>
-EndOfFile
-) > /etc/apache2/sites-enabled/000-default
+source $vidaas_admin_repo_path/admin/$vidaas_branch/root/etc/apache2/sites-available/vidaas.sh > /etc/apache2/sites-available/vidaas
+if ! [ -h /etc/apache2/sites-enabled/vidaas ] ; then
+  ln -s /etc/apache2/sites-available/vidaas /etc/apache2/sites-enabled/000-vidaas
+fi
+rm /etc/apache2/sites-enabled/000-default > /dev/null
 service apache2 restart
 
 echo "project node install completed"
