autocreate debug user

diff --git a/admin/branches/WithRoles/scripts/vidaas-install b/admin/branches/WithRoles/scripts/vidaas-install
--- a/admin/branches/WithRoles/scripts/vidaas-install
+++ b/admin/branches/WithRoles/scripts/vidaas-install
@@ -22,4 +22,12 @@ if ! apt-get -qqy install $default_packages ; then
   exit 1
 fi
 
+if [ -n "$debug_user" ] ; then
+  echo "creating debug user..."
+  if ! adduser --disabled-login --group vidaas ; then
+    echo "failed to create vidaas user"
+    exit 1
+  fi
+fi
+
 . $vidaas_admin_repo_path/admin/$vidaas_branch/scripts/vidaas-${vidaas_node_type}node-install
