merged changes

diff --git a/admin/branches/WithRoles/scripts/vmware-bootstrap b/admin/branches/WithRoles/scripts/vmware-bootstrap
--- a/admin/branches/WithRoles/scripts/vmware-bootstrap
+++ b/admin/branches/WithRoles/scripts/vmware-bootstrap
@@ -25,25 +25,22 @@ EndOfFile
 echo "Checking out admin repository into $vidaas_admin_repo_path"
 if [ ! -f /usr/bin/svn ] ; then
   if ! apt-get -qqy install subversion ; then
-    echo "Unable to install subversion package"
-    exit 1
+    echo "Unable to install subversion package" ; exit 1
   fi
 fi
 mkdir -p $vidaas_admin_repo_path 2> /dev/null
 if ! cd $vidaas_admin_repo_path ; then
-  echo "repository path $vidaas_admin_repo_path invalid"
-  exit 1
+  echo "repository path $vidaas_admin_repo_path invalid" ; exit 1
 fi
 if ! svn checkout $vidaas_admin_repo_url ; then
-  echo "svn checkout failed"
-  exit 1
+  echo "svn checkout failed" ; exit 1
 fi
 
 if [ -f $vidaas_admin_repo_path/admin/systems/`cat /etc/hostname` ] ; then
   ln -s $vidaas_admin_repo_path/admin/systems/`cat /etc/hostname` /etc/vidaas/system-settings
   . /etc/vidaas/system-settings
 else
-  echo "no config in $vidaas_admin_repo_path/admin/systems/`cat /etc/hostname`"
+  echo "no config in $vidaas_admin_repo_path/admin/systems/`cat /etc/hostname`" ; exit 1
 fi
 echo "boostrap completed"
 
